name: checksonme_merchant
description: Merchant app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  font_awesome_flutter: ^8.11.0
  provider: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  qr: ^2.0.0
  qr_flutter: ^4.0.0
  animated_widgets: ^1.0.6  # Pretty sure this one is not needed anymore, must check later
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: "assets/launchers/playstore.png"
  ios: true
  image_path_ios: "assets/launchers/appstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/buttons/
    - assets/launchers/

  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Black.ttf
        - asset: fonts/Merriweather-BlackItalic.ttf
    - family: Molle
      fonts:
        - asset: fonts/Molle-Italic.ttf
