name: checksonme_merchant
description: Merchant app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  font_awesome_flutter: ^8.11.0
  provider: ^5.0.0
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: "assets/launchers/playstore.png"
  ios: true
  image_path_ios: "assets/launchers/appstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/launchers/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
